title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://icmoore.github.io/test_gh_pages

aux_links:
  Template Repository: https://github.com/icmoore/test_gh_pages

plugins:
  - jekyll-default-layout
